### PR TITLE
update logo

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by jmchilton** [comment]
Won't this be too large? Also I feel like the purpose of the older variant was to highlight getgalaxy.org - I am not sure this variant does that. Can we just replace the top part with a smaller version of the new logo?

**Comment by martenson** [comment]
oh maybe you meant the orange getgalaxy.org as the 'top part'?

I think that is visualy terrible. We can just include getgalaxy.org under it as a hyperlink but I would rather not bastardize our logo this way. :)

**Comment by jmchilton** [comment]
If we drop the getgalaxy.org orange text (which I am happy to do - but we should ask more people) - then there is no point to the logo at all right? I would rather just have a text link and get to the content quicker.

**Comment by martenson** [comment]
The logo is a brand - we should include it for consistent feel and familiarity.

**Pull request merged**
